# Generated by Django 6.0.3 on 2026-04-05 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=5)),
                ('score', models.PositiveSmallIntegerField()),
                ('total', models.PositiveSmallIntegerField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quiz.player')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='quiz_quizre_date_d34420_idx'), models.Index(fields=['player', 'date'], name='quiz_quizre_player__692157_idx')],
            },
        ),
    ]
