# Generated by Django 6.0.3 on 2026-04-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('day', models.PositiveSmallIntegerField(db_index=True)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('pages', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['month', 'day'], name='quiz_event_month_21df01_idx')],
            },
        ),
    ]
